name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Cycloside/Cycloside.csproj


      - name: Build
        run: dotnet build Cycloside/Cycloside.csproj --configuration Release --no-restore

      - name: Test
        if: ${{ hashFiles('**/*Tests.csproj') != '' }}
        run: dotnet test --no-build --verbosity normal
